const express = require("express") 
const router = express.Router() 
let friends = [const express = require("express") 
const router = express.Router() 
let friends = [const express = require("express") 
const router = express.Router() 
let friends = [const express = require("express") 
const router = express.Router() 
let friends = [const express = require("express") 
const router = express.Router() 
let friends = [const express = require("express") 
const router = express.Router() 
let friends